// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: calculator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CalculatorServiceClient is the client API for CalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalculatorServiceClient interface {
	Calculate(ctx context.Context, in *CalculatorRequest, opts ...grpc.CallOption) (*CalculatorResponse, error)
	CalculateManyTimes(ctx context.Context, in *CalculatorRequest, opts ...grpc.CallOption) (CalculatorService_CalculateManyTimesClient, error)
	CalculateLongClientStream(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_CalculateLongClientStreamClient, error)
	CalculateBiDirectional(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_CalculateBiDirectionalClient, error)
}

type calculatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculatorServiceClient(cc grpc.ClientConnInterface) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) Calculate(ctx context.Context, in *CalculatorRequest, opts ...grpc.CallOption) (*CalculatorResponse, error) {
	out := new(CalculatorResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculatorService/Calculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) CalculateManyTimes(ctx context.Context, in *CalculatorRequest, opts ...grpc.CallOption) (CalculatorService_CalculateManyTimesClient, error) {
	stream, err := c.cc.NewStream(ctx, &CalculatorService_ServiceDesc.Streams[0], "/calculator.CalculatorService/CalculateManyTimes", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceCalculateManyTimesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculatorService_CalculateManyTimesClient interface {
	Recv() (*CalculatorResponse, error)
	grpc.ClientStream
}

type calculatorServiceCalculateManyTimesClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceCalculateManyTimesClient) Recv() (*CalculatorResponse, error) {
	m := new(CalculatorResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) CalculateLongClientStream(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_CalculateLongClientStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &CalculatorService_ServiceDesc.Streams[1], "/calculator.CalculatorService/CalculateLongClientStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceCalculateLongClientStreamClient{stream}
	return x, nil
}

type CalculatorService_CalculateLongClientStreamClient interface {
	Send(*CalculatorRequest) error
	CloseAndRecv() (*CalculatorResponse, error)
	grpc.ClientStream
}

type calculatorServiceCalculateLongClientStreamClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceCalculateLongClientStreamClient) Send(m *CalculatorRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorServiceCalculateLongClientStreamClient) CloseAndRecv() (*CalculatorResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(CalculatorResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) CalculateBiDirectional(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_CalculateBiDirectionalClient, error) {
	stream, err := c.cc.NewStream(ctx, &CalculatorService_ServiceDesc.Streams[2], "/calculator.CalculatorService/CalculateBiDirectional", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceCalculateBiDirectionalClient{stream}
	return x, nil
}

type CalculatorService_CalculateBiDirectionalClient interface {
	Send(*CalculatorRequest) error
	Recv() (*CalculatorResponse, error)
	grpc.ClientStream
}

type calculatorServiceCalculateBiDirectionalClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceCalculateBiDirectionalClient) Send(m *CalculatorRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorServiceCalculateBiDirectionalClient) Recv() (*CalculatorResponse, error) {
	m := new(CalculatorResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculatorServiceServer is the server API for CalculatorService service.
// All implementations must embed UnimplementedCalculatorServiceServer
// for forward compatibility
type CalculatorServiceServer interface {
	Calculate(context.Context, *CalculatorRequest) (*CalculatorResponse, error)
	CalculateManyTimes(*CalculatorRequest, CalculatorService_CalculateManyTimesServer) error
	CalculateLongClientStream(CalculatorService_CalculateLongClientStreamServer) error
	CalculateBiDirectional(CalculatorService_CalculateBiDirectionalServer) error
	mustEmbedUnimplementedCalculatorServiceServer()
}

// UnimplementedCalculatorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCalculatorServiceServer struct {
}

func (UnimplementedCalculatorServiceServer) Calculate(context.Context, *CalculatorRequest) (*CalculatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculate not implemented")
}
func (UnimplementedCalculatorServiceServer) CalculateManyTimes(*CalculatorRequest, CalculatorService_CalculateManyTimesServer) error {
	return status.Errorf(codes.Unimplemented, "method CalculateManyTimes not implemented")
}
func (UnimplementedCalculatorServiceServer) CalculateLongClientStream(CalculatorService_CalculateLongClientStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method CalculateLongClientStream not implemented")
}
func (UnimplementedCalculatorServiceServer) CalculateBiDirectional(CalculatorService_CalculateBiDirectionalServer) error {
	return status.Errorf(codes.Unimplemented, "method CalculateBiDirectional not implemented")
}
func (UnimplementedCalculatorServiceServer) mustEmbedUnimplementedCalculatorServiceServer() {}

// UnsafeCalculatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalculatorServiceServer will
// result in compilation errors.
type UnsafeCalculatorServiceServer interface {
	mustEmbedUnimplementedCalculatorServiceServer()
}

func RegisterCalculatorServiceServer(s grpc.ServiceRegistrar, srv CalculatorServiceServer) {
	s.RegisterService(&CalculatorService_ServiceDesc, srv)
}

func _CalculatorService_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculatorService/Calculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Calculate(ctx, req.(*CalculatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_CalculateManyTimes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CalculatorRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServiceServer).CalculateManyTimes(m, &calculatorServiceCalculateManyTimesServer{stream})
}

type CalculatorService_CalculateManyTimesServer interface {
	Send(*CalculatorResponse) error
	grpc.ServerStream
}

type calculatorServiceCalculateManyTimesServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceCalculateManyTimesServer) Send(m *CalculatorResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CalculatorService_CalculateLongClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServiceServer).CalculateLongClientStream(&calculatorServiceCalculateLongClientStreamServer{stream})
}

type CalculatorService_CalculateLongClientStreamServer interface {
	SendAndClose(*CalculatorResponse) error
	Recv() (*CalculatorRequest, error)
	grpc.ServerStream
}

type calculatorServiceCalculateLongClientStreamServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceCalculateLongClientStreamServer) SendAndClose(m *CalculatorResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorServiceCalculateLongClientStreamServer) Recv() (*CalculatorRequest, error) {
	m := new(CalculatorRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CalculatorService_CalculateBiDirectional_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServiceServer).CalculateBiDirectional(&calculatorServiceCalculateBiDirectionalServer{stream})
}

type CalculatorService_CalculateBiDirectionalServer interface {
	Send(*CalculatorResponse) error
	Recv() (*CalculatorRequest, error)
	grpc.ServerStream
}

type calculatorServiceCalculateBiDirectionalServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceCalculateBiDirectionalServer) Send(m *CalculatorResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorServiceCalculateBiDirectionalServer) Recv() (*CalculatorRequest, error) {
	m := new(CalculatorRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculatorService_ServiceDesc is the grpc.ServiceDesc for CalculatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalculatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _CalculatorService_Calculate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CalculateManyTimes",
			Handler:       _CalculatorService_CalculateManyTimes_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CalculateLongClientStream",
			Handler:       _CalculatorService_CalculateLongClientStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "CalculateBiDirectional",
			Handler:       _CalculatorService_CalculateBiDirectional_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "calculator.proto",
}
